// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace ProjectManagment.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20241015155303_AddNewEmployeeSeedData")]
    partial class AddNewEmployeeSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EmployeeId");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6595d486-6a51-49c3-b4a3-b55f432f2a61"),
                            Age = 24,
                            FirstName = "Emre",
                            LastName = "CEVİK",
                            Position = "Junior Developer",
                            ProjectId = new Guid("a88e2ba1-f7cc-4d6b-a995-69575dc7e8b7")
                        },
                        new
                        {
                            Id = new Guid("d66f8e6b-b499-4f68-8595-afeb4d95a5db"),
                            Age = 23,
                            FirstName = "Taner",
                            LastName = "Bilinmiyor",
                            Position = "Mid Developer",
                            ProjectId = new Guid("f98e1ba1-f7cc-4d6b-a995-69575dc7e8b7")
                        },
                        new
                        {
                            Id = new Guid("e47a2f9b-7e6a-4b4e-bf78-d9e8e2d5cbb3"),
                            Age = 31,
                            FirstName = "Ali",
                            LastName = "Midci",
                            Position = "Mid Developer",
                            ProjectId = new Guid("f98e1ba1-f7cc-4d6b-a995-69575dc7e8b7")
                        });
                });

            modelBuilder.Entity("Entities.Models.Project", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProjectId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ID = new Guid("f98e1ba1-f7cc-4d6b-a995-69575dc7e8b7"),
                            Description = "Web Application Programming Interface",
                            Field = "Computer Science",
                            Name = "Asp.Net Core Web API Project 1"
                        },
                        new
                        {
                            ID = new Guid("a88e2ba1-f7cc-4d6b-a995-69575dc7e8b7"),
                            Description = "Another Web Application Programming Interface",
                            Field = "Information Technology",
                            Name = "Asp.Net Core Web API Project 2"
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Project", "Project")
                        .WithMany("Employees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Entities.Models.Project", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
